### ISSUE TITLE
Flag support enhancement 

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/goflags#11]
Currently, we have many use cases where we wanted to support optional string flags with default values, few examples:-

`output` flag with the default value set to `log` and also supports replacing `log` to the user-provided input string.

Example:-

```
./tool -output
```

This will store output from the tools to the `logs` folder or file as defined.

```
./tool -output my_logs
```
This will store output from the tools to the `my_logs` folder or file as defined.

Currently, this behavior is not supported hence we have multiple tools with additional flags, i.e one boolean flag to define use, and another flag to define file/folder location, supporting this will cut down those flags and better UX.

Here are multiple examples where two flags can be merged into one after this support.

`sr / srd` - httpx
`rc / rdb` - nuclei
`ut / ud`  - nuclei

**Comment by brenol** [comment]
Hello @ehsandeep!

I was looking at this issue but I did not understand what should be implemented here, as the behavior already seems to be that one:

config.yml:
```yml
name: logs
```

Code:
```go
package main

import (
    "fmt"

    "github.com/projectdiscovery/goflags"
)

func main() {
    fs := goflags.NewFlagSet()

    var field, configFile string
    fs.StringVar(&configFile, "config", "", "Set the config file")
    fs.StringVar(&field, "name", "defaultValue", "Set the username")

    if err := fs.Parse(); err != nil {
        fmt.Println(err)
        return
    }

    if configFile != "" {
        // from file
        if err := fs.MergeConfigFile(configFile); err != nil {
            fmt.Println(err)
            return
        }
    }

    fmt.Printf("Result: [%s]\n", field)
}

```

Running that without passing either `config` or `name` arguments, using defaultValue:
```sh
$ go run main.go
Result: [defaultValue]
```

Only config.yml being used:
```sh
$ go run main.go -config config.yml           
Result: [logs]
``` 


Setting flag & config.yml:
```sh
$ go run main.go -config ./config.yml -name 'Hello, world!'
Result: [Hello, world!]
``` 

Did I misunderstand the issue here?

Thanks!

**Comment by forgedhallpass** [comment]
@ChandanChainani 
It doesn't contradict from a requirement point of view. The fact that the current library does not support it, that's one thing, but that's exactly why this issue exists, to implement it.

**Comment by ChandanChainani** [comment]
@forgedhallpass I like to work on it and I tried ways but non works what your suggestion can you point me the direction or should work in flag library and after if merged then if require in goflag

**Comment by vzamanillo** [comment]
I don't know if this is even possible because the flag value check it's an internal go flags thing

https://github.com/golang/go/blob/master/src/flag/flag.go#L1087

If we are going to do this we have to do it before parsing the flags (overwritting the flag) or via custom parse implementation.

thoughts?
